apiVersion: v1
kind: ReplicationController        ## 副本控制器RC
metadata:
  name: mysql      ## RC的名称，全局唯一
spec:
  replicas: 1      ## Pod副本期待数量
  selector:
    app: mysql       ## 符合目标的Pod拥有此标签
  template:      ## 根据此模板创建Pod实例
    metadata:
      labels:
        app: mysql      ## 副本Pod拥有的标签对应RC的selector
    spec:
      containers:          ## Pod内容器定义部分
      - name: mysql           ## 容器的名称
        image: mysql:5.5       ## 容器的镜像
        ports:
        - containerPort: 3306    ## 容器暴露的端口号
        env:                 ## 注入容器的环境变量
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
